aws_region = "us-east-1"
environment = "management"
project_name = "LandingZone"
terraform_state_bucket = "aws-landing-zone-terraform-state-2024"
terraform_state_dynamodb_table = "aws-landing-zone-terraform-lock" 